app/__init__.py
from flask import Flask

# Import of Blueprints
from .api.routes import api
from .site.routes import site

# Library to generate log file
from loguru import logger


def create_app():
    app = Flask(__name__)

    app.register_blueprint(api)
    app.register_blueprint(site)

    # Create(if doesn't exist already) a logger directory
    # located in the PATH above
    logger.add("logs/app.log")

    return app

app/api/routes.py
from flask import abort, Blueprint, request
import requests

# Library to calculate distance between two coordinates
import haversine as hs
from haversine import Unit

# Library to generate log file
from loguru import logger


# instance of Blueprint api with a url_prefix
api = Blueprint('api', __name__, url_prefix='/api')


# Route that calculate the distance between MKAD and the
# address typed by the user. It must be coordinate(first lng
# then lat) and float.
@api.route("/distance/<float:lng>/<float:lat>", methods=["GET"])
def distance(lng, lat):
    if(request.method == 'GET'):
        if(lng and lat):
            # As said im README.md, the parameter used to calculated inside
            # MKAD was the distance between Moscow(center of the radius) and
            # MKAD(edge of radius), which is equal 12.9 kms or 8 miles.
            # So, it calculate the distance between Moscow and the address
            # gave by the user less 12.9 kms or 8 miles.
            moscow = (37.622513, 55.75322)
            address = (lng, lat)
            dist = round(hs.haversine(moscow, address), 1)
            if(dist <= 12.9):
                logger.error({'ValueError': 'Distance inside MKAD.'})
                return abort(400, {'ValueError': 'Distance inside MKAD.'})
            else:
                dist = round(dist - 12.9, 1)
                miles = round(hs.haversine(
                    moscow, address, unit=Unit.MILES), 1) - 8
                json = {"Address": {"Coordinates": {"Longitude": f"{lng}",
                                                    "latitude": f"{lat}"}
                                    },
                        "Distances": {"Kilometers": f"{dist}",
                                      "Miles": f"{miles}"}}
                logger.success(f"{json}")
                return json
        else:
            logger.error({'ValueError': 'Distance inside MKAD.'})
            abort(400, "The coordinates in URL are invalid.")


# Route to get data of a certain place. It can be a name(Moscow) or
# coordinates(37.622513 55.75322, 37.622513,55.75322).
@api.route("/getdata/<address>", methods=["GET"])
def getdata(address):
    if(request.method == 'GET'):
        data = requests.get(
            f"https://geocode-maps.yandex.ru/1.x/?apikey=085b7527-0c65-43e9-b0e7-86b52fb93ffe&geocode={address}&format=json&lang=en-US&results=1")
        # Here I selected the number of results founds when a search is done but has no results founds.
        # To achieve it, I made a navigation inside the JSON response of the API to found the parameter "found"
        # and raise and Exception 400 when it's equal to 0.
        points = data.json()["response"]["GeoObjectCollection"]["metaDataProperty"]["GeocoderResponseMetaData"]["found"]
        for point in points:
            if(point == "0" or point == 0):
                logger.error({"ValueError": "name or coordinates in URL are invalid"})
                return abort(400, {"ValueError": "name or coordinates in URL are invalid"})
            else:
                logger.success({"Address": f"{address}"})
                return data.json()

app/site/routes.py
from flask import abort, Blueprint, render_template, request
import requests

# Library to calculate distance between two coordinates
import haversine as hs
from haversine import Unit

# Library to generate log file
from loguru import logger


# instance of Blueprint site
site = Blueprint('site', __name__)


# Route of home page with instructions of how to consume the API
# and anothers functionalities.
@site.route('/', methods=['GET'])
def index():
    return render_template('home_page.html')


# Route to calculate the distance based on longitude and latitude
# inserted as input and submmited with buttons by the user in a more
# visual display as alternative of the route API.
@site.route("/distance", methods=["POST"])
def distance():
    if(request.method == 'POST'):
        lng = request.form["longitude"]
        lat = request.form["latitude"]
        # As said im README.md, the parameter used to calculated inside MKAD
        # was the distance between Moscow(center of the radius) and
        # MKAD(edge of radius), which is equal 12.9 kms or 8 miles.
        # So, it calculate the distance between Moscow and the address gave
        # by the user less 12.9 kms or 8 miles.
        moscow = (37.622513, 55.75322)
        if(lng == "" or lng == " " or lat == "" or lat == " "):
            return abort(400, "The coordinates or name in URL are invalid.")
        else:
            address = (float(lng), float(lat))
            dist = round(hs.haversine(moscow, address), 1)
            if(dist <= 12.9):
                return render_template('home_page.html',
                                       value_error=True)
            else:
                km = round(dist - 12.9, 1)
                miles = round(hs.haversine(
                    moscow, address, unit=Unit.MILES), 1) - 8
                json = {"Address": {"Coordinates": {"Longitude": f"{lng}",
                                                    "latitude": f"{lat}"}
                                    },
                        "Distances": {"Kilometers": f"{km}",
                                      "Miles": f"{miles}"}}
                logger.success(f"{json}")
                return render_template('home_page.html',
                                       address=address,
                                       kilometers=km,
                                       miles=miles)


# Route to display data of an address based on longitude and latitude or
# city and street name inserted as input and submmited with buttons by the user
# in a more visual display as alternative of the route API. Does the same thing
# of the Blueprint API /api/getdata but a little more friendly to understand
# how does it work.

# Here it's important to notice that was divided the search address in 2 parts:
# One searching by the city or street name
# Another searching by the coordinates longitude and latitude

# Route that search by city or steet
@ site.route("/getdata/city", methods=["POST"])
def getdata_city():
    if(request.method == 'POST'):
        address = request.form["city"]
        if(address):
            data = requests.get(
                f"https://geocode-maps.yandex.ru/1.x/?apikey=085b7527-0c65-43e9-b0e7-86b52fb93ffe&geocode={address}&format=json&lang=en-US&results=1")
            # Here I selected the number of results founds when a search is done but has no results founds.
            # To achieve it, I made a navigation inside the JSON response of the API to found the parameter "found"
            # and raise and Exception 400 when it's equal to 0.
            points = data.json()[
                "response"]["GeoObjectCollection"]["metaDataProperty"]["GeocoderResponseMetaData"]["found"]
            for point in points:
                if(point == "0" or point == 0):
                    return abort(400, "The coordinates or name in URL are invalid.")
                else:
                    logger.success({"Address": f"{address}"})
                    return data.json()
        else:
            return abort(400, "The coordinates or name in URL are invalid.")


# Route that search by longitude and latitude
@ site.route("/getdata/coordinate", methods=["POST"])
def getdata_coordinate():
    if(request.method == 'POST'):
        lng = request.form["longitude"]
        lat = request.form["latitude"]
        if(lng == "" or lng == " " or lat == "" or lat == " "):
            return abort(400, "The coordinates or name in URL are invalid.")
        else:
            address = (float(lng), float(lat))
            data = requests.get(
                f"https://geocode-maps.yandex.ru/1.x/?apikey=085b7527-0c65-43e9-b0e7-86b52fb93ffe&geocode={address}&format=json&lang=en-US&results=1")
            # Here I selected the number of results founds when a search is
            # done but has no results founds. To achieve it, I made a and
            # raise and Exception 400 when it's equal to 0.
            points = data.json()[
                "response"]["GeoObjectCollection"]["metaDataProperty"]["GeocoderResponseMetaData"]["found"]
            for point in points:
                if(point == "0" or point == 0):
                    return abort(400, "The coordinates or name in URL are invalid.")
                else:
                    logger.success({"Coordinate": f"{address}"})
                    return data.json()

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/main.css">
    {% block head %} {% endblock %}
</head>
<body>
    <div class='container'>
        {% block body %} {% endblock %}
    </div>
    <footer class="container text-center">
        <br>
        <hr class="col-10" style="margin-left: 150px;">
        <p style="font-weight: bold;">&copy; Pedro M. Guedes - 08/2021</p>
      </footer>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</body>
</html>

app/templates/home_page.html
{% extends 'base.html' %}


{% block head %}
    <title>MKAD API - Home Page</title>
{% endblock %}

{% block body %}
    <br>
    <h1>Welcome to MKAD API</h1>
    <hr>


    <br>
    <h4>Type an address to calculate the distance between <strong><u>Moscow Ring Road</u></strong> and the specified address.</h4>
    <br>
    <h4>If the address is inside <strong><u>MKAD</u></strong> it won't be calculated.</h4>
    <br>
    <br>



    <div class="container">

      <div class="row d-inline-block">

        <form action="{{ url_for('site.distance') }}", method="POST">
  
          <div class="form-group col-6 float-left">
            <p><strong><u>Calculate distance</u>: </strong></p>
            <p><strong><u>Obs</u>: </strong>To do so, enter a <strong>valid coordinate(longitude, latitude)</strong> that is
              <strong><u>NOT INSIDE MKAD</u></strong>.</p>
               <p>Examples:
               <br>
               <strong><u>Longitude</u>: </strong> 40.406635</p>
               <strong><u>Latitude</u>: </strong> 56.129057</p>

               <br>
               <br>
            
            <label for="longitude" class="form-label"><strong><u>Longitude</u>: </strong></label>
            <input type="float" name="longitude" class="form-control" id="longitude">
            <br>

            <label for="latitude" class="form-label"><strong><u>Latitude</u>: </strong></label>
            <input type="float" name="latitude" class="form-control" id="latitude">


            <button type="submit" class="btn btn-outline-light btn-md bg-info"><strong>Calculate</strong></button>
          </div><!-- form-group -->
        </form><!-- form - calculate distance -->
    
    
        <form action="{{ url_for('site.getdata_coordinate') }}", method="POST">
    
            <div class="form-group col-6 float-right">
              <p><strong><u>Search Address</u>: </strong></p>
              <p><strong><u>Obs</u>: </strong>To do so, enter a <strong>valid coordinate(longitude, latitude)</strong>
                or the <strong>name of street, city.</strong></p>
                <p>Examples:
                  <br>
                  <strong><u>Longitude</u>: </strong> 40.406635</p>
                  <strong><u>Latitude</u>: </strong> 56.129057</p>
                <p><strong><u>City or Address</u>: </strong> vladimir</p>
                <br>
              
              <label for="longitude" class="form-label"><strong><u>Longitude</u>: </strong></label>
              <input type="float" name="longitude" class="form-control" id="longitude">
              <br>
  
              <label for="latitude" class="form-label"><strong><u>Latitude</u>: </strong></label>
              <input type="float" name="latitude" class="form-control" id="latitude">

              <button type="submit" class="btn btn-outline-light btn-md bg-danger"><strong>Search by Coordinate</strong></button>
            </form><!-- form - search address by coordinate -->


              <br>
              <br>
              <form action="{{ url_for('site.getdata_city') }}", method="POST">
              <label for="city" class="form-label"><strong><u>City or Street</u>: </strong></label>
              <input type="text" name="city" class="form-control" id="city">

              <button type="submit" class="btn btn-outline-light btn-md bg-danger"><strong>Search by name</strong></button>
            </div><!-- form-group -->
          </form><!-- form - search address by name -->
          
      </div><!-- class row -->

    </div><!-- container -->
    


        <br>
        <br>
        <h1>Results</h1>
        <hr>


        {% if value_error %}
        <br>
        <h4><strong>The coordinate is inside the MKAD.</strong></h4>
        <br>
        {% endif %}


        {% if kilometers and miles %}
          <p><strong>Address Coordinate:</strong> {{ address }}</p>
          <p><strong>Distance in kilometers:</strong> {{ kilometers }}</p>
          <p><strong>Distance in miles:</strong> {{ miles }}</p>
        {% endif %}


        <br>
        <br>
        <br>
        <h1>How to use the API</h1>
        <hr>

        <h4>There are <strong>two routes</strong> and <strong>two buttons</strong> you can use:</h4>
        <br>
        <ul>
          <li>
            <h4><strong>/api/distance/lng/lat</strong></h4>
            <button type="submit" class="btn btn-outline-light btn-sm bg-info" disabled><strong>Blue button</strong></button>
            <br>
            <br>
            <p>Calculate the distance in kilometers and miles between MKAD and the coordinate, first longitude then latitude, for example:</p>
       
            <a href="http://127.0.0.1:5000/api/distance/40.406635/56.129057">http://127.0.0.1:5000/api/distance/40.406635/56.129057</a></p>
            
          </li>
          <br>
          <br>
          <li>
            <h4><strong>/api/getdata/city_name_or_coordinate</strong></h4>
            <button type="submit" class="btn btn-outline-light btn-sm bg-danger" disabled><strong>Red button</strong></button>
            <br>
            <br>
            <p>Give some data and coordinates in case you don't know to calculate via API.</p>
            <p>Insert coordinates and names as the examples above:
              <br>
              <br>
              <a href="http://127.0.0.1:5000/api/getdata/40.406635,56.129057">http://127.0.0.1:5000/api/getdata/40.406635,56.129057</a></p>
              <a href="http://127.0.0.1:5000/api/getdata/vladimir">http://127.0.0.1:5000/api/getdata/vladimir</a></p>
          </li>
          <br>
          <li>More examples in <a href="https://yandex.com/dev/maps/geocoder/doc/desc/examples/geocoder_examples.html">https://yandex.com/dev/maps/geocoder/doc/desc/examples/geocoder_examples.html</a></li>
        </ul>
{% endblock %}